export interface WeddingGuest {
  id: string;
  name: string;
  salutation: string; // "Anh", "Chị", "Cô", "Chú", "Bạn", "Gia đình"...
  company: string; // "FPT Telecom", "Ngân hàng VCB", "Hội Nhiếp Ảnh"...
  address: string; // "Hà Nội", "Quận 1, TP. HCM", "Đà Nẵng"...
  group: string; // "Đồng nghiệp", "Bạn Đại Học", "Họ Hàng Nhà Trai", "Họ Hàng Nhà Gái"...
  tableNumber: string; // "Bàn 01", "Bàn VIP"...
  plusOne: string; // "và Người Thương", "và Gia Đình", "1 vé"...
  phone?: string;
  note?: string;
}

export type GuestSortField = 'company' | 'address' | 'group' | 'tableNumber' | 'name';
